### ISSUE TITLE
Bug: Multiple books from same author are merged into one book

### ISSUE THREAD

**Issue by trymeouteh** [PaulWoitaschek/Voice#1091]
If you have multiple books from the same author they will not show up as multiple books but one single book. Here is an example below of the file structure and when I add the root folder to the voice app, I add it as "Folder with multiple books"

- Root
- - Author 1
- - - Book 1
- - - - File 1.mp3
- - - - File 2.mp3
- - - - File 3.mp3
- - - Book 2
- - - - File 1.mp3
- - - - File 2.mp3
- - - - File 3.mp3

**Comment by ndsharp** [comment]
This is a problem for me too. Though it seems to get the chapters right for each book it's lumped together. 

I would much rather have an option of seeing each book listed individually. Some books in a series I have read and some listened. Grouping them into a sub-menu for the series would be fine.

**Comment by adrinux** [comment]
Just came across this too, only worse since the per book sub folders were named by book title without numbers, Voice plays them in alphabetical order, ie the wrong order :)

After experimenting it seems the solution is simply to move the books to the top level Audiobook folder you've told Voice all your books were in - it currently ignores the Author folder anyway.

(The only problem is if you're using a different App on Server or Desktop that makes use of the Author folder, you loose the ability to easily sync files. Personally I'm currently only listening on my phone...)

**Comment by PaulWoitaschek** [comment]
Yes that is the solution. Thanks for explaining.

**Comment by danielmmmm** [comment]
Calling this a solution is ignoring the problem :-D. It's like saying "Get through the window when the door is broken".

Btw., I am not complaining. There are enough alternatives. This is just feedback from someone who used Voice for a few weeks.

**Comment by PaulWoitaschek** [comment]
The feature will come back as 7.2. You can already grab the release from Github

**Comment by danielmmmm** [comment]
Thanks, v7.2 is definitely an improvement. You obviously put a lot of effort into Voice. Sorry to say that 2 folder levels just make the overall problem less of a hassle. Imagine an "author folder" containing some subfolders for single novels, and some subfolders for cycles or series containing more subfolders for each book of the cycle/series. Also, generally assuming that single files in any folder are separate audio books has to cause trouble for some users.

Again, I am not complaining, just giving feedback :-D. For me, only a true folder navigation, without any kind of library function to import books, makes sense (or a library function that replicates the folder structure). If other people, like @trymeouteh, think the same, maybe you don't have to invest a lot of time in fixing something that still doesn't please us, but that you and your happy Voice users actually like and think is working well.
Just to make sure, because this is the Internet: I am not being ironic here. Obviously, you coded Voice the way you like an Audiobook reader to work. And that's what counts in the end.
