### ISSUE TITLE
Feedback/Suggestions for 6.x

### ISSUE THREAD

**Issue by newhinton** [PaulWoitaschek/Voice#1150]
First, the new look is sleek!

I do have some suggestions to make:

1. Startup of Voice now takes way longer than before. Opening the app results in an empty screen without audiobooks, and populating takes way longer than 5.x
2. I always liked that the progressbar was in individual colors. Can we get them back?
3. Does this app use the new color api? The new "flat" look of voice would be perfect for that.
4. The Cover deserves to be rounded aswell, on all three places
5. The title in the playerview looks odd, maybe it could be centered and above a cover that has margins and rounded corners?
6. Search - Since the "categories" are removed and we can see every book in the list, a search has become necessary to find a book in a bigger collection. The "audiobook-folder" icon can be hidden in the settings if at least one folder has been added, and then been replaced by a search icon. This way we would not add too many icons while hiding stuff that is not regularly accessed

And something i noticed on "every" version of voice, the app requires a rather large amount of power. In comparison:
Vlc ~3% for 1 hour 30 min
Voice ~14% for 2 hours 15 min
Phonograph ~9% for 2 hours

Those numbers are reported by my settings, so they may be flawed in some way, and also they are not what i would call scientifically sound. But if this can be confirmed on other devices aswell, this may be worth investigating.

Im willing to create pr's, just give me a note! If you'd like i can also try to get better data on the powerconsumption.

Edit: added search

**Comment by PaulWoitaschek** [comment]
Thanks for the detailed feedback, that's very valueable.

Can we repurpose this ticket for the performance and create dedicated ones for the other issues?

> Startup of Voice now takes way longer than before. Opening the app results in an empty screen without audiobooks, and populating takes way longer than 5.x

I'm not sure this is true. Before 6.0, the whole book list was loaded blockingly on start which was basically freezing the frames. In 6.x it startes immediately but takes a moment to load.

Besides to that I tried to improve the general performance in this PR and would be happy for a PR:
https://github.com/PaulWoitaschek/Voice/pull/1151

> I always liked that the progressbar was in individual colors. Can we get them back?

I think it doesn't work too good with the dynamic colors, that's why I left it out.

> Does this app use the new color api? The new "flat" look of voice would be perfect for that.

By the new color api you mean the material you dynamic colors? YES! 👍 

> The Cover deserves to be rounded aswell, on all three places. The title in the playerview looks odd, maybe it could be centered and above a cover that has margins and rounded corners?

I'd be happy to review a PR with some screenshots

> Search - Since the "categories" are removed and we can see every book in the list, a search has become necessary to find a book in a bigger collection. The "audiobook-folder" icon can be hidden in the settings if at least one folder has been added, and then been replaced by a search icon. This way we would not add too many icons while hiding stuff that is not regularly accessed

Yep, that would be the next thing on my list (after the data migration strategy). PR welcome!

> Power Usage

If the linked PR does not already solve it to a larger degree please open a separate ticket for that.
The main thing that I assume uses power is that voice is constantly updating the database to not lose any progress. But just a guess, I did not measure it.
