### ISSUE TITLE
Cannot update Play Store version with Github release

### ISSUE THREAD

**Issue by NLLAPPS** [PaulWoitaschek/Voice#1380]
### What happened?

Hi and thank you. I have been enjoying your app for some time. Just noticed you have resumed working on it for sometime and wanted to test [6.0.0-beta01](https://github.com/PaulWoitaschek/Voice/releases/tag/6.0.0-beta01)

I cannot update Play Store version with 6.0.0-beta01. Package conflict error.

Will you be updating Play Store version at all or should I use Github version?

### Version

5

**Comment by njmdietrich** [comment]
I'm not the author, but I think I can answer your questions. It is expected that you can't update the google play version with the github apks, because the packages have a different signature. I also don't think that the google play version will get any beta releases, so the next update there will likely be when version 6.0.0 is properly released. Whether you want to replace the google play version for the github version and gain the ability to install beta releases is up to you, of course.

**Comment by PaulWoitaschek** [comment]
You can Join the Play Beta:
https://github.com/PaulWoitaschek/Voice/wiki/FAQ
Play and GitHub releases have a different signing, therefore can not be updated. 
However you can uninstall one and install the other afterwards. 
But if you are already on Google Play, joining the Play Beta is the way to go.

**Comment by PaulWoitaschek** [comment]
From 6.0.0-rc8 on, you should be able to install a github release on top of a play release and vice-versa.
