### ISSUE TITLE
Version 6 is a disaster

### ISSUE THREAD

**Issue by m3thm4th** [PaulWoitaschek/Voice#1444]
### What happened?

F-Droid got an update from version 5.0.2 to 6.0.7 and the app seems to be broken.
- All open files are now gone, luckily the progresses are stored in a list in `Old book posistions`, but now I have to open them and seek manually one by one.
- The `See all` buttons disappeared, so I can only see a handful of files and I don't know how to access the others.
- Holding the buttons doesn't show the tooltip about what they do.
- The color schemes both for light and dark theme were more beautiful before.

### Version

6.0.7

**Comment by jawz101** [comment]
I just wiped the app data and I'll manually find where i left off. I'd rather start with a clean slate with what looks like a change that had to be done for newer Android version storage permissions.  Considering the change, I'd rather just reset it up than rely on the app update to go smoothly is what I'm saying.

**Comment by newhinton** [comment]
On my device just re-adding the book locations and waiting for the scan to complete "restored" the 5.x state. 

However, this was a deliberate (and nessessary) change due to the requirement of the [Storage Access Framekwork](https://developer.android.com/about/versions/11/privacy/storage) as @jawz101 already stated.

> The See all buttons disappeared, so I can only see a handful of files and I don't know how to access the others.

There should not be books that are hidden. Every book in your library should show up in the corresponding category, you have to scroll to find it. Maybe it has not yet been added because the scanner can be somewhat slow and it takes a while. (A search is planned, see #1150)

> The color schemes both for light and dark theme were more beautiful before.

The reason for this is that voice now uses the material-you themes. If you have a device with Android 12, it will now follow the color-scheme of your device.

**Comment by strider72** [comment]
Losing all my bookmarks was a huge inconvenience. At least the times were saved textually in the "old files" section, but why not simply update that old data to the new books???

**Comment by PaulWoitaschek** [comment]
Please be polite and don't use words like "disaster". 
Please create one issue per topic so the discussion can stay focused.

**Comment by PaulWoitaschek** [comment]
> Losing all my bookmarks was a huge inconvenience. At least the times were saved textually in the "old files" section, but why not simply update that old data to the new books???

This should work if you update from 5.x to 6.x. 
There were a few users that got an in-between Update where it doesn't work but for the vast majority of users the data should be migrated.
