### ISSUE TITLE
v7 forgets current book in Android Auto

### ISSUE THREAD

**Issue by jedfonner** [PaulWoitaschek/Voice#1765]
### Overview

When Android Auto starts, if Voice was the last audio app used, it will start but it won't remember the current book. Instead, it shows Press to Open at which point it just shows the list of available books.  I have to scroll down to find the current book.  Once selected, it does resume playing where I last left off.  This was never an issue in version 6.

![PXL_20230405_203206637 MP](https://user-images.githubusercontent.com/344481/230215035-148e7fd3-5541-4162-b614-e8fac55368b0.jpg)

### How to reproduce

1. Use Voice to start playing a book
2. Start Android auto
3. Notice that Voice doesn't remember the current book

### Version

7.0.5

### Android Version

Android 13

### Device Model

Pixel 6a

**Comment by firecat53** [comment]
An additional symptom I've noticed is that the playback speed and volume boost are now reset to default and have to be adjusted on the phone after it connects. (Pixel 6 up to date, Voice 7.0.5 from F-Droid). Thanks!

**Comment by BartemX** [comment]
Same here after latest update (version 7.0.5)

**Comment by jedfonner** [comment]
This seems to be fixed in version 7.0.7.  I'm not seeing the problem anymore.  Thanks!

**Comment by jedfonner** [comment]
I noticed that this problem isn't fully fixed.  I've noticed that sometimes it still forgets the current book in Android auto and I'm forced to re-pick it.

**Comment by yeo-gen** [comment]
I also have a problem with the list of recent books. Previously, the list was sorted from the most recent to the oldest. Now the list has changed the sorting order, so the last book that is currently playing is at the bottom of the list, and it takes a long time to scroll down. Please restore the sorting list from the most recent at the top to the oldest at the bottom.
(1+ 8 Pro, Android 13, Voice 7.0.7)

**Comment by R2E4** [comment]
I have the same issue since the update to 7.0.7.
On a Samsung S23, Android 13, Voice 7.0.7)
When i start the Voice app on the smartphone the actual book is always listed on top and it works as expected.
When i connect the smartphone to Android Auto i can see the Voice app, but no book is selected and playback does not start.
When i manually select the actual book form the list in Android Auto it starts playback at the correct position.
If i stop the car, disconnect the phone and reconnect the phone immediately it starts the playback as well automatically.
If there are some hours between or if i reconnect the phone next day again no actual book is selected and no playback starts and it shows the screen as documented in the issue above.
In Android Auto the option "Start music automatically" is active as before with the older version of Voice
