### ISSUE TITLE
Resuming playback not possible without restarting app

### ISSUE THREAD

**Issue by tomaThomas** [PaulWoitaschek/Voice#1777]
### Overview

When the media player notification is dismissed while Voice is open, an audiobook cannot be resumed anymore until the app is restarted (the play button does nothing, at least for the android 13 media player this is the case).

This is especially annoying because the notification disappears by itself if the audiobook is paused for a while and the app needs to be restarted manually.

### How to reproduce

1. Start and then pause an audiobook
2. Swipe away the media player notification
3. Try to resume the audiobook

### Version

7.0.6

### Android Version

Lineage 13

### Device Model

OnePlus 6

**Comment by PaulWoitaschek** [comment]
Can you make a Screencast? These steps don't reproduce for me:

Uploading screen-20230409-121610.mp4…

**Comment by PaulWoitaschek** [comment]
https://user-images.githubusercontent.com/743462/230767306-9a02b61e-8fa9-48f8-b0fe-674000eae3e3.mp4

**Comment by tomaThomas** [comment]
Here's is a screencast, but maybe it is an issue with my phone as I wasn't able to reproduce it in an emulator.
The only log output is this:
`V/VoicePlayer$updateLastPlayedAt:179: Update Test Audio: lastPlayedAt to 2023-04-09T17:48:50.362711Z`
I'll look into it more deeply when I've got a bit more time

https://user-images.githubusercontent.com/17884154/230789214-e9fcaad6-402f-44f8-9915-ec95ec60f60d.mp4

**Comment by tomaThomas** [comment]
It only happens if 'Pin media player' is disabled in the android settings, see the video

https://user-images.githubusercontent.com/17884154/231126234-29199398-2edd-42e9-a110-4ce465e78d6e.mp4

**Comment by wimmstr** [comment]
Wanted to open an Issue, but this seems related. Just pasting it here. 

**Priority**: Low
**Description**: Unable to resume Playback after sudden Bluetooth Disconnect (i.e. Turning off Car Engine -> Bluetooth pairing to radio stops without warning)

**Workaround:** 
Either: Force stop app, or play different audiobook
Or: Manually pause playback before disconnecting Bluetooth connection.

Thanks for the awesome App!

**Comment by bkw777** [comment]
I have the same problem and I have that same pin media player setting off. However even so I can't reproduce the problem immediately. I even tried playing other media player apps that I normally use (AntennaPod, Spotify) while Voice was paused, which replaces the Voice notification with the other media apps. It may require some passage of time between pausing and trying to play again. I don't *think* bluetooth matters because I *think* I've had it happen with no bt involved along the way, but I will have to double check that.

I think the problem only started with 7.0.6. But my os updated recently too so it's possible it's the latest version of lineageos. But I think the problem is newer than that.

It will take some time to nail down the pattern I guess.

I'll wait untill it happens again and try to be aware of everything that happened (was bt involved, how long paused, etc), and then downgrade to 7.0.5 and see if it happens again.

**Comment by bkw777** [comment]
Dang it just happened again on 7.0.6, and I cannot tell you what the cause is. I had paused a book last night, played another media player, and left it like that over night. No bluetooth involved. In themorning, resuming the book worked fine. I stopped again and did nothing much for a couple hours, either reading articled in Feedly or just not touching the phone. No bluetooth, no other media players, didn't touch any notifications. And just now after only an hour or so, play does not work.

I know this is marked resolved but until the update shows up in fdroid I was still trying to determine the pattern or rule things out at least. I ruled out bluetooth and notifications and other players and even the passage of time, but didn't figure out anything that it might be.

Maybe it's the passage of an hour or so specifically *without* any other media player in between.

**Comment by bkw777** [comment]
I have discovered that force-close is not the only way to get play working again. When the play button doesn't work, you can also select some other book, and play will work on that, then switch back to the original book, and play will now work on that book that didn't before, without ever force-closing the app.
