### ISSUE TITLE
Audiobook desynchronized with timeline

### ISSUE THREAD

**Issue by CristianKerr** [PaulWoitaschek/Voice#1911]
### Overview

Hi I have several audiobooks as mp3's. When I play them they are desynchronizing with the shown timeline and when I pause and play it then jumps back or forward depending on which direction it gets desynced. Somehow this is unpredictable though: even if I go to particular chapter at particular timestamp (even if its the first thing I do) it jumps to a wrong part (e.g. 2 minutes after the chapter start). The media player that I found works correctly (when I go to time of chapter start, the audio really starts the chapter there) is e.g. VLC on desktop.
Any ideas why this happens and what can I do to mitigate the issue? Can this be something with bit rate or something? Thank you

### How to reproduce

I can share a sample in some private channel. 

### Version

Latest from f-droid

### Android Version

Anrdoid 13

### Device Model

OnePlus6 but I tested on multiple devices

**Comment by PaulWoitaschek** [comment]
Thanks for the report. The answer is basically this:
https://github.com/google/ExoPlayer/issues/9408#issuecomment-957282047

On VLC it's mostly working because it indeeed scans the whole file. That however is slow on mobile, especially with the variety of low spec devices out there. 

To mitigate the issue you could convert your files to AAC / m4a / m4b. 

Once exoplayer supports the best effort strategy, Voice will make use of it.

**Comment by CristianKerr** [comment]
Hi, thanks for a quick reply! I will check the link and try to convert the audio. Thanks a lot!
