### ISSUE TITLE
Add Sorting options for audiobooks.

### ISSUE THREAD

**Issue by andremina** [PaulWoitaschek/Voice#724]
Please include the following details in your bug report:

It'll be great if I can sort all audiobooks by (date Added)

App-Version:
Phone Name:
Android Version:

**Comment by Wizek** [comment]
Yes please! I'd especially like to sort by last played date, so that my current/most recently played books are at the top. Supporting manual reordering could be nice as a workaround too for my usecase in case that would be easier to implement.

Potentially related issue: #689 

@PaulWoitaschek, what do you think?

**Comment by Plastix** [comment]
Sorting options, including `date added`, have been implemented with https://github.com/PaulWoitaschek/Voice/pull/765.
