### ISSUE TITLE
Incorrect Chapters for mp3 files.

### ISSUE THREAD

**Issue by lemnos** [PaulWoitaschek/Voice#782]
I have several mp3 files with chapter information which don't play correctly. Specifically there seems to be an offset when using the chapter information contained within the files. Manually inspecting the files with ffmpeg and playing them with mplayer suggests that the chapter information is correct and that the app is not jumping to the correct locations.

**Comment by versavius** [comment]
Is it possible to upload the MP3 files or one of them with your findings so we can look at this information? It should help the Devs spot what is going wrong more easily?

**Comment by PaulWoitaschek** [comment]
Nothing actionable to do here without media.

**Comment by womanlike** [comment]
I have the same issue with a long audiobook. The chapter beginning positions encoded into the file as id3 tags are correct (I checked in Audacity), but when I try to jump to a chapter in Voice, there is an error of about 1 minute. At the same time, chapter end positions seem to be used correctly by Voice, which results in a weird seeking experience as I try to find the beginning of a chapter. @PaulWoitaschek I will send you the media to your email.

**Comment by womanlike** [comment]
As an addition, if I pause this audiobook and don't resume to playing it right away (e.g. wait about a minute), the position where Voice continues will be *ahead* of the position where I paused, even with the auto-rewind function enabled. In my case, the "offset"/error for this book is about 1 minute, and I have 5 seconds of auto-rewind, which doesn't cancel the offset. This doesn't happen if I resume to playing right away.

@versavius I'm not sure either, but in case it helps, it's a 10+ hour audiobook I purchased on Audible, downloaded as a DRM'd .aax, and decrypted and converted to a 128 kbps CBR .mp3 in a single command using ffmpeg 4.3.4 (LAME3.100): `ffmpeg -activation_bytes 1234abcd -i input.aax -b:a 128k output.mp3`. I have two such audiobooks and the other one too has these  issues in Voice.

**Comment by PaulWoitaschek** [comment]
Does that also reproduce in the beta?

Else this might be caused by an incorrect mp3 file:
https://github.com/google/ExoPlayer/issues/6698

For audible I usually recommend to directly convert to m4b, for example:
```
ffmpeg -activation_bytes 1234abcd -i input.aax -acodec copy out.m4b
```

**Comment by womanlike** [comment]
@PaulWoitaschek using your command I get the following errors (and an empty output file):

> MB rate (92160000) > level limit (16711680)

and

> Could not find tag for codec h264 in stream #0, codec not currently supported in container
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:0 --

The "MB" above means [macroblocks](https://superuser.com/a/1612594), and the highest rate of macroblocks/second supported in H.246 is 16,711,680, at [level 6.2](https://en.wikipedia.org/wiki/Advanced_Video_Coding#Levels), which level is used by default in response to this command. What do you recommend? I was searching for ffmpeg encoding options to use with M4B (like they exist for [MP3](https://trac.ffmpeg.org/wiki/Encode/MP3)), hoping I can modify something to fit into the limit, but nothing came up.

If it helps, MediaInfo has the following to say about the source file:

> General
Format                                   : aax 
Codec ID                                 : aax  (aax /M4B /mp42/isom)
...
Overall bit rate mode                    : Constant
Overall bit rate                         : 129 kb/s
...
Writing library                          : Apple QuickTime
...
Audio
...
Format                                   : aavd-40-2
Codec ID                                 : aavd-40-2
...
Bit rate mode                            : Constant
Bit rate                                 : 128 kb/s

**Comment by womanlike** [comment]
@PaulWoitaschek To answer your earlier question: I don't know where to access the beta version of the app, but I did play same MP3 in Voice 6.0.0-alpha19 and the bug was reproduced.

**Comment by PaulWoitaschek** [comment]
The file that was sent to me is very strange. 

```
Input #0, mp3, from '2013-complex-ptsd.mp3':
  Metadata:
    major_brand     : aax 
    minor_version   : 1
    compatible_brands: aax M4B mp42isom
    date            : 2018
    title           : Complex PTSD: From Surviving to Thriving
    artist          : Pete Walker
    album_artist    : Pete Walker
    album           : Complex PTSD: From Surviving to Thriving
    genre           : Audiobook
    copyright       : ©2014 Pete Walker (P)2018 Tantor
    encoder         : Lavf58.45.100

  Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 128 kb/s
    Metadata:
      encoder         : Lavc58.91
```

So it's a file with an mp3 extension that has an mp4 header with a mp3 stream. I wonder what produces such a broken file.
Also this:
`Duration: 10:29:05.84, start: 0.025056, bitrate: 128 kb/s`
The file does itself starts at 0.025, that's strange.

I could not convert it to m4a but what worked was converting it to matroska:

```
ffmpeg -i 2013-complex-ptsd.mp3 -map_metadata 0 -vn out.mkv
```

You might remove the -vn, then it should probably keep the cover but will be quite slower.

**Comment by womanlike** [comment]
@PaulWoitaschek Thank you for looking into this. Let me recap a bit because I think you missed some details. My starting point was the AAX file which I converted to MP3 via the command I described [above](https://github.com/PaulWoitaschek/Voice/issues/782#issuecomment-1136419896), so that's what produced the broken result. (Which is strange that it's broken, the method seems to be in wide use.) I sent you both the AAX (together with the activation bytes in the filename) and the MP3 in email. Could you please confirm whether it's better to convert the AAX to MKV, the MP3 to MKV as you did, or something else?

Also, as I mentioned earlier, this is not my only Audible book that produces this behavior with Voice.

**Comment by versavius** [comment]
Did this ever get resolved?

**Comment by womanlike** [comment]
@versavius it may have. Paul recommended me some other practices via mail, none of which seemed to work separately a month ago. Today I tried it again with a book and so far I no longer experience the issue.

(I want to add that a month ago, I also tried removing the chapter data from the resulting MP3 (`ffmpeg -i audiobook.mp3 -f ffmetadata metadata.txt`, manually remove the chapter data from metadata.txt, then `ffmpeg -i audiobook.mp3 -i metadata.txt -map_metadata 1 -map_chapters 0 -codec copy audiobook--nochapter.mp3`), and I had the same inconsistencies when Voice tried to resume to where I left off. So, at least in this case, as opposed to the title of this issue, the problem was independent of chapters.)

Here's what seems to be working for me so far:

1. I downloaded a fresh copy of the AAX from Audible.
2. I went to https://audible-converter.ml/.
3. I opened the AAX with the tool.
4. I let the tool guess my activation bytes.
5. I changed the Output Format to "AAC m4b" and the Operating System to "Linux." (This is supposed to result in the command `ffmpeg -y -activation_bytes  -i  './input.aax' -codec copy 'output.m4b'`. The output will be an M4A file, but don't worry about this.)
6. I let the tool do the conversion.
7. I opened Voice to take note of my listening position because I may lose it as I will delete the old audio file.
8. I updated Voice to 6.1.2 from https://github.com/PaulWoitaschek/Voice/releases.
9. I deleted the old audio file and copied the new one in its place.

**Comment by versavius** [comment]
Interesting, I have been using Voice again and with two audio books I have not had the issue i mentioned before.

You have made me think, is the issue we are getting from audio books downloaded from one particular source?

What I am thinking is if the issues everyone is having is audio books downloaded from audible (which is where most of mine, if not all come from), could the issue be down to audible doing something odd with their books occasionally?

**Comment by versavius** [comment]
> @versavius it may have. Paul recommended me some other practices via mail, none of which seemed to work separately a month ago. Today I tried it again with a book and so far I no longer experience the issue.
> 
> (I want to add that a month ago, I also tried removing the chapter data from the resulting MP3 (`ffmpeg -i audiobook.mp3 -f ffmetadata metadata.txt`, manually remove the chapter data from metadata.txt, then `ffmpeg -i audiobook.mp3 -i metadata.txt -map_metadata 1 -map_chapters 0 -codec copy audiobook--nochapter.mp3`), and I had the same inconsistencies when Voice tried to resume to where I left off. So, at least in this case, as opposed to the title of this issue, the problem was independent of chapters.)
> 
> Here's what seems to be working for me so far:
> 
> 1. I downloaded a fresh copy of the AAX from Audible.
> 2. I went to https://audible-converter.ml/.
> 3. I opened the AAX with the tool.
> 4. I let the tool guess my activation bytes.
> 5. I changed the Output Format to "AAC m4b" and the Operating System to "Linux." (This is supposed to result in the command `ffmpeg -y -activation_bytes  -i  './input.aax' -codec copy 'output.m4b'`. The output will be an M4A file, but don't worry about this.)
> 6. I let the tool do the conversion.
> 7. I opened Voice to take note of my listening position because I may lose it as I will delete the old audio file.
> 8. I updated Voice to 6.1.2 from https://github.com/PaulWoitaschek/Voice/releases.
> 9. I move the old audio file somewhere outside of Voice's audiobook folder and copied the new one in its place.

Just a thought, but do you have the original audiobook that gave you issues? If so can you try and see if you can replicate the issue?

I'll have a look and see if I can find any that I had issues with but i'll likely have to listen to them again to get to that spot so it won't be easy for me to replicate the issue.

**Comment by womanlike** [comment]
@versavius I could dig up the old MP3 and triage it, but I won't, I'm just too tired of this issue. I agree it would be nice to identify the source of the problem, but the developer himself doesn't seem to be interested in that, so as long as it works for me, I won't pursue this further.

**Comment by suy** [comment]
I can reproduce this issue with the latest version of Voice. The MP3 plays correctly on two different desktop open source players ([Haruna](https://github.com/KDE/haruna) and VLC). The metadata says that the end of first chapter is 6:42, and that is right on those players (the chapter ends at that time), but not on Voice, which is still about a minute "late", meaning that the chapter still has about of one minute of play time, but the play time indicator (the time, the progress bar, etc.) say otherwise.

I can do more testing if you want, or provide privately the MP3 file. Would it be useful if I used a clock to measure how much time is the player actually taking to reach the 6:42 mark? I had the playback speed to 100%, but maybe there is something causing it to be off.
