### ISSUE TITLE
how to rescan the audiobooks folder?

### ISSUE THREAD

**Issue by mishaxz** [PaulWoitaschek/Voice#892]
Hi, how do you rescan the library? I can't figure it out... I did the initial scan a few weeks ago and that worked fine but I copied some new .m4b files into a new subfolder of my audiobooks folder (that is configured in voice as my audiobooks folder) ... and it doesn't detect it and I can't find where in the UI to manually rescan. 

note: all my audiobooks are in subfolders so being in subfolders is not the problem

Please include the following details in your bug report:

App-Version: latest
Phone Name: android
Android Version: pi

**Comment by 0rAX0** [comment]
I usually add stuff and they appear in the list without me doing anything. I don't think you can initiate a rescan from the UI AFAIK.

**Comment by thw0rted** [comment]
Just to be clear, what are your Audiobook Folders ("bookmark" button in home screen), and where are you putting files?  My only folder is `/storage/{SD card ID}/Audio Books` and under there I have `Some Book/some_book.m4a`, `Another Book/another_book.m4a` etc etc.  As soon as I add a new folder+file and switch back to Voice, the book shows up in the list.

**Comment by mishaxz** [comment]
my audiobooks folder is called "AudioBooks" .. it is on the main drive of the phone, where all the other folders like Downloads are ... the initial scan works fine, it just never rescans and I can't find any way to manual rescan. I have many audiobooks, usually they have their own folders under AudioBooks.. some might be multiple levels deep as well for books from the same author (although they are not all like that).. I can't check the actual path since I currently have it uninstalled because I can't use it if I can't rescan, although I would like to use it. I do not know if Voice was running when I copied the new books into the folder.. that might be the problem.. Voice might not have been running when I transferred the files. But it definitely doesn't rescan afterwards on my device.. which is a K20 Pro if that matters at all

**Comment by thw0rted** [comment]
Voice is very.... particular, about the folder structure.  If you have the file(s) for book 1 in `/AudioBooks/Book1/` and the files for book 2 in `/AudioBooks/Book2/`, etc, with *no* nesting, no separate folders per author, etc, you might have better luck.  There's a bunch of issues here asking for better handling of different structures, different ways of organizing content, etc, but one of them have been resolved yet.  If you're willing to flatten out the structure of your folder so that every book is at the top level, you could try again and hopefully auto-detection starts working again.  You could also give a "thumbs-up" reaction to #809 and related issues, to show interest.
