### ISSUE TITLE
Can't install GitHub releases over F-droid version

### ISSUE THREAD

**Issue by leafcutterant** [PaulWoitaschek/Voice#902]
I have the latest version that was released through F-droid (3.6.1). I want to upgrade to the latest available (open source: 4.3.2, proprietary: 4.3.3), but with both versions I get "App not installed." I thought of removing the F-droid version and then installing one of these, but I fear I would lose my positions in my audiobooks and my settings, and there's no option to export settings (at least not in 3.6.1).

Any way I can get around this?

Thanks for the great UX.

App-Version: 3.6.1
Android Version: LineageOS 15.1

**Comment by nr458h** [comment]
Instead of asking for a workaround we probably could ask for look into why the builds for fdroid are failing?
That would be great. Thanks in advance

**Comment by xorbital** [comment]
The reason is that the packages distributed by F-Droid are signed by F-Droid, they guarantee you to match the source code they were built from.
In comparison the versions you downloaded are signed with a different (the developers) key, and Android won't allow you to update an app with a mismatching key / signature (which is a good thing!)

You could try to backup the app's data with adb, this *could* work.
The easiest solution is probably to manually re-set your playback states.

There should probably be a new issue tracking the progress of getting updates via F-Droid

**Comment by PaulWoitaschek** [comment]
Yes due to different signatures you can't install one on top of another.
