### ISSUE TITLE
[Feature Request] spread out the playback controls more

### ISSUE THREAD

**Issue by RalfKo** [PaulWoitaschek/Voice#907]
I often accidently hit wrong buttons. would be great if you could use the complete width of my screen to make the play-control-buttons bigger or introduce more whitespace between them.

**Comment by kanjieater** [comment]
Came to request the same thing. Smart Audiobook player, while rough looking, has really nice and large buttons for those of us with big hands and big phones

**Comment by thw0rted** [comment]
I don't have a wireframe tool handy, but it occurred to me today that the cover art takes up a huge amount of space but doesn't *do* anything. If you could come up with a good play/pause overlay, so that the whole thing is effectively a button, you could split the bottom into even quarters for the four remaining playback controls.

I'm aware that the cover art can be double tapped to pause but it's not advertised and wouldn't serve to replace the current (visible) button without some kind of overlay.

**Comment by PaulWoitaschek** [comment]
Done

**Comment by RalfKo** [comment]
thx!
