### ISSUE TITLE
Persistent notification

### ISSUE THREAD

**Issue by dmcalcada** [PaulWoitaschek/Voice#921]
Please include the following details in your bug report:

App-Version: Latest
Phone Name: OnePlus 7 Pro
Android Version: Android 10

In my OnePlus 7 Pro, in Android 10, this app in always being triggered and a notification is always being shown, even if there isn't anything playing.
Please try it.

**Comment by cityeyes** [comment]
I'm having a similar issue on the OnePlus 6. The notification is almost always active regardless of whether or not I've run it. At first I thought it was because I had the widget, but upon deleting the widget, it's still there.

**Comment by thebiffman** [comment]
This happens to me aswell in Android 10 on Oneplus 6. Restarting the phone and first thing that pops up is the Voice notification.

**Comment by innesst** [comment]
I get a notification on restart with Android 10 pixel 2, but it can be swiped away.

**Comment by cityeyes** [comment]
Android 10 final beta on OnePlus 6 and it's unswipeable. It becomes swipeable when I open content, but shortly returns afterwards.

Here's [a video](https://www.youtube.com/watch?v=u8N3LKFT3NA&feature=youtu.be) of how it behaves.

The final version of Android 10 is coming for my phone, but I suspect since I'm on a RC currently, there haven't been large enough changes to fix this notification issue.

**Comment by Kardzhilov** [comment]
This is still an issue, hopefully someone can look at it as last update was in May. 
Personally i only notice it happening if i connect my phone to a Bluetooth headset.

**Comment by njmdietrich** [comment]
I thought I'd chip in my experiences - I'm running android 10 (crdroid) on a pocophone f1.
I don't get a persistent notification on reboot or at any other time, but i do not have a bluetooth headset to test if that is an issue. So if this issue was due to the android version, it's either fixed now or doesn't universally apply to all devices.

**Comment by cityeyes** [comment]
I thought the problem had been resolved because, for some reason, the notification was gone when I got up this morning after updating to the newest version of Android (A beta build of 10 on Oneplus 6), but it's back now. Not sure what triggers it, but I do regularly use bluetooth and I did have my phone connected to bluetooth in my car this morning, so maybe it "wakes up" when bluetooth comes around and simply gets stuck in the notifications bar. Not sure, honestly. I'll try to keep a closer eye on it in the meantime.

**Comment by d0rf3n** [comment]
App-Version: Latest
Phone Name: OnePlus 6
Android Version: Android 10

Same, always on notification. Can't be dismissed. And contains no information except app name title.

**Comment by ben-henderson** [comment]
Can confirm on oneplus 7t pro it is still and issue

**Comment by gil** [comment]
Same here since Android update :/

I have to keep disabling notifications when I'm not using and enabling again while playing to be able to control what's playing.

App-Version: 4.3.2
Phone Name: OnePlus 6T
Android Version: Android 10

**Comment by PaulWoitaschek** [comment]
Should be fixed in 5.0.0. You can test the rc in the releases tab on github (or you just wait :) )

**Comment by CreamyCookie** [comment]
I just had this problem in 5.0.1

OnePlus 3T (Android 9)

**Comment by thw0rted** [comment]
I just noticed this and I wonder if it's the same issue from #974 ?  It sounds like similar symptoms, but I didn't experience it myself until April, post-5.0.
