### ISSUE TITLE
Introduce Google Play Beta Testing

### ISSUE THREAD

**Issue by egvimo** [PaulWoitaschek/Voice#959]
First of all I would like to say that I really like the app and use it very often. And I'm very grateful for the effort and time you put into it.

And just because I use the app very often, I want it to be stable. But the last update has some bugs that make the app almost unusable on a device (#957).

So I would like to ask you to consider introducing Google Play Beta Testing. So the app could be tested before a release. Also Google offers a staged rollout as far as I know.

All this would be half as bad if the development would proceed more rapidly, but since weeks there is a no progress (no bug fixes). And the last update before version 5 was in May 2019. Many bugs and feature requests were closed with reference to upcoming features or Android updates. But these are still missing.

By the way: is there a way to downgrade? 

Maybe there are others who can help to push the development forward (if you don't have time or something). I'm not able to do that, unfortunately.

I would appreciate any feedback and thanks again for the great app!

**Comment by PaulWoitaschek** [comment]
I have very limited time right now. But there are issues open and if someone fixes them I'll merge and release them.
Voice does not have that many users and Beta releases don't work because there is just too little data.
The version you are using is on a staged rollout with 10% rollout (meaning 1600 installations), that is the bare minimum to find issues already.

You can always install an older version from the github release page.

**Comment by egvimo** [comment]
Thanks for your feedback and clarification.
