### ISSUE TITLE
Architecture variants for F-Droid

### ISSUE THREAD

**Issue by SebiderSushi** [PaulWoitaschek/Voice#978]
As [stated in another issue](https://github.com/PaulWoitaschek/Voice/issues/957#issuecomment-603989363), version 5.0.1 now contains ffmpeg libraries to parse metadata.
Since F-Droid does not support app bundles, users are left to download and install an apk file that contains libraries for all supported architectures. This currently implies an apk size of 85MB, while previous apks where even smaller than 5MB.

However, F-Droid supports building and publishing apk variants by architecture. That way, F-Droid users could be given the option to download and install just what's necessary for their architecture even without app bundle or split-apk support by F-Droid.

**Comment by PaulWoitaschek** [comment]
I commented on the fdroid issue for supporting app bundles.

https://gitlab.com/fdroid/fdroidserver/-/issues/731

I'd rather not complicate the build process but instead have fdroid handle this.

**Comment by TacoTheDank** [comment]
@PaulWoitaschek Because F-Droid will very likely not support split APKs for a long time from now, I have an idea I'd like to try to set up. We could set up the splits like [this](https://github.com/Telegram-FOSS-Team/Telegram-FOSS/blob/master/TMessagesProj/build.gradle) (but have them only generate for opensource builds using gradle magic). Of course, this means updating https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/de.ph1b.audiobook.yml will have to be [manual](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.telegram.messenger.yml#L1389) now, but that isn't an issue, really.

https://developer.android.com/studio/build/configure-apk-splits



May I?

**Comment by shuvashish76** [comment]
@PaulWoitaschek any updates?

**Comment by shuvashish76** [comment]
https://gitlab.com/fdroid/fdroiddata/-/issues/3217
@PaulWoitaschek any updates?
